# Negative case for the relay edge-case test: with relay.enable = false,
# Syncthing's *live* config must genuinely have relaysEnabled = false —
# proving the option isn't a no-op.
#
# Not checked via journalctl grepping for "relays.syncthing.net": Syncthing
# always starts with its own built-in defaults (relays on) for the few
# seconds before syncthing-init.service pushes our declarative config
# through the REST API — found via an actual VM test that a naive "never
# appears in the log" assertion fails every time, even when the module
# wiring is correct, because that brief default-then-override window is
# expected/inherent, not a bug. The real, timing-independent question is
# what Syncthing's *own* config reports once the push has actually
# completed.
import json

machine.wait_for_unit("syncthing.service", timeout=60)
machine.succeed("systemctl is-active syncthing.service")
machine.wait_for_unit("syncthing-init.service", timeout=60)

machine.sleep(3)
# GET /rest/config still needs an API key (Syncthing's CSRF protection
# rejects unauthenticated requests outright, "CSRF Error" 403) — found
# via an actual VM test, not documented anywhere in this module. The key
# is generated by Syncthing itself into its own config on disk.
import re
config_xml = machine.succeed("cat /var/lib/syncthing/.config/syncthing/config.xml")
api_key_match = re.search(r"<apikey>([^<]+)</apikey>", config_xml)
assert api_key_match is not None, config_xml
api_key = api_key_match.group(1)
live_config = json.loads(
    machine.succeed(
        f"curl -sk -H 'X-API-Key: {api_key}' https://127.0.0.1:8384/rest/config"
    )
)
assert live_config["options"]["relaysEnabled"] is False, (
    f"relay.enable = false but Syncthing's live config still has "
    f"relaysEnabled = {live_config['options']['relaysEnabled']!r} after "
    f"syncthing-init.service completed — the option isn't reaching "
    f"Syncthing's actual config"
)

print("=== Syncthing no-relay test done: relay.enable = false genuinely disables the relay client ===")
